# Generated by Django 5.1 on 2024-11-13 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_branch_description_branch_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='image',
            field=models.CharField(max_length=255),
        ),
    ]
